uploaded
listasCss
	^ 'h2 {
    font-family: Frutiger, Helvetica, Trebuchet, "Trebuchet MS", Arial, sans-serif;
    font-size: 12px;
    line-height: 14px;
    color: #E3E3EB;
}

div.botoneras {
    display: flex;
    flex-direction: row;

}

#bloque {
    width: 990px;
    margin-right: auto;
    margin-left: auto;
    margin-top: 2px;
    margin-bottom: 2px;
    display: block;
}

#bloque #container #rubros .categoria {
    font-family: Arial, Helvetica, sans-serif;
    font-size: 12px;
    font-weight: bold;
    line-height: 26px;
    background-image: url(http://localhost:8080/files/IndutelFileLibrary/fondoRubros.gif);
    display: block;
    text-align: center;
    width: 215px;
    height: 26px;
    color: #E0EBF5;
    text-decoration: none;
    margin-bottom: 3px;
    margin-right: auto;
    margin-left: auto;
}

p#textoNormal {
    font-family: Frutiger, Helvetica, Trebuchet, "Trebuchet MS", Arial, sans-serif;
    font-size: 12px;
    line-height: 14px;
    color: #000000;
    margin-bottom: 10px;
    text-align: left;
}

div#container {
    width: 978px;
    float: left;
    background-color: #E3E3EB;
    border: 6px solid #FFFFFF;
    margin: 0px;
    text-align: center;
    background-image: url(http://localhost:8080/files/IndutelFileLibrary/bordeInfo.jpg);
    background-position: 309px;
    padding-top: 0px;
    padding-right: 0px;
    padding-bottom: 0px;
    padding-left: 0px;
    background-repeat: repeat-y;
}

div#links {
    height: 28px;
    width: 990px;
    display: block;
    border-top-width: 6px;
    border-top-style: solid;
    border-top-color: #FFFFFF;
    clear: both;
    font-size: 12px;
    line-height: 24px;
    font-weight: normal;
    color: #000000;
    text-indent: 15px;
    padding-top: 0px;
    background-color: #FFFFFF;
}

h2.titular {
    font-size: 3em;
    text-align: center;
}

div.separador1 {
    display: block;
    height: 24px;
    width: 10px;
    float: left;
    margin: 0px;
    padding: 0px;
    border-top-width: 0px;
    border-right-width: 0px;
    border-bottom-width: 0px;
    border-left-width: 0px;
    border-top-style: none;
    border-right-style: none;
    border-bottom-style: none;
    border-left-style: none;
}

.link_fondo {
    font-family: Arial, Helvetica, sans-serif;
    color: #339966;
    text-decoration: none;
    height: 26px;
    padding-right: 12px;
    padding-left: 0px;
    display: block;
    background-image: url(http://localhost:8080/files/IndutelFileLibrary/b5_r1_c3.gif);
    font-size: 12px;
    line-height: 26px;
    background-repeat: repeat-x;
    font-weight: bold;
    width: auto;
    text-align: center;
    float: left;
    margin: 0px;
}

a.link_fondo {
    font-family: Arial, Helvetica, sans-serif;
    color: #339966;
    text-decoration: none;
    height: 26px;
    padding-right: 12px;
    padding-left: 0px;
    display: block;
    background-image: url(http://localhost:8080/files/IndutelFileLibrary/b5r1c3Gif);
    font-size: 12px;
    line-height: 26px;
    background-repeat: repeat-x;
    font-weight: bold;
    width: auto;
    text-align: center;
    float: left;
    margin: 0px;
}

img.link_izq {
    heigth: 26;
    width: 7;
}

p#titulo1 {
    font-family: Frutiger, Helvetica, Trebuchet, "Trebuchet MS", Arial, sans-serif;
    font-size: 26px;
    line-height: 26px;
    color: #E3E3EB;
    font-weight: bold;
    margin-top: 10px;
}

p#textoLogo {
    font-family: Frutiger, Helvetica, Trebuchet, "Trebuchet MS", Arial, sans-serif;
    font-size: 14px;
    line-height: 14px;
    color: #FFFF00;
    font-weight: bold;
    width: 153px;
    display: block;
    text-align: center;
    height: 24px;
}

img .logo {
    max-width: 13em;
    max-height: 5em;
}

div.caja {
    display: flex;
    background-color: #225996;
}

div.caja2 {
    border-color: black;
    border-style: solid;
}

p.testo {
    font-weight: bold;
    font-size: 1em;
    font-style: normal;
    font-family: sans-serif;
}

div.cabeza {
    display: flex;
    flex-direction: row;
}'