hooks
style
	^ '


#bloque #container #rubros #categoria {
    font-family: Arial, Helvetica, sans-serif;
    font-size: 12px;
    font-weight: bold;
    line-height: 26px;
    background-image: url(http://localhost:8080/files/IndutelFileLibrary/fondoRubros.gif);
    display: block;
    text-align: center;
    width: 215px;
    height: 26px;
    color: #E0EBF5;
    text-decoration: none;
    margin-bottom: 3px;
    margin-right: auto;
    margin-left: auto;
}

p#textoNormal {
    font-family: Frutiger, Helvetica, Trebuchet, "Trebuchet MS", Arial, sans-serif;
    font-size: 12px;
    line-height: 14px;
    color: #000000;
    margin-bottom: 10px;
    text-align: left;
}

id#bloque {
    width: 990px;
    margin-right: auto;
    margin-left: auto;
    margin-top: 2px;
    margin-bottom: 2px;
    display: block;
}

.categoria {
    font-family: Arial, Helvetica, sans-serif;
    font-size: 12px;
    font-weight: bold;
    line-height: 26px;
    background-image: url(http://localhost:8080/files/IndutelFileLibrary/catalogo.jpg);
    display: block;
    text-align: center;
    width: 215px;
    height: 26px;
    color: #E0EBF5;
    text-decoration: none;
    margin-bottom: 3px;
    margin-right: auto;
    margin-left: auto;
}

div.container {
    width: 978px;
    float: left;
    background-color: #E3E3EB;
    border: 6px solid #FFFFFF;
    margin: 0px;
    text-align: center;
    background-image: url(http://localhost:8080/files/IndutelFileLibrary/bordeInfo.jpg);
    background-position: 309px;
    padding-top: 0px;
    padding-right: 0px;
    padding-bottom: 0px;
    padding-left: 0px;
    background-repeat: repeat-y;
}

ul#rubros{
    font-family: Arial, Helvetica, sans-serif;
    font-size: 12px;
    font-weight: bold;
    line-height: 26px;
    background-image: url(http://localhost:8080/files/IndutelFileLibrary/fondoRubros.gif);
    display: block;
    text-align: center;
    width: 215px;
    height: 26px;
    color: #E0EBF5;
    text-decoration: none;
    margin-bottom: 3px;
    margin-right: auto;
    margin-left: auto;
}

'